# Generated by Django 5.0.3 on 2024-09-26 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApp', '0002_remove_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='task',
        ),
    ]
