# Generated by Django 5.0.3 on 2024-09-26 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApp', '0003_rename_name_task_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
